### ISSUE TITLE
Tests should include `register()`

### ISSUE THREAD

**Issue by staticfloat** [JuliaRegistries/RegistryTools.jl#10]
Unfortunately, we don't seem to test the full `register()` codepath, which ended up with a broken release (easily fixed by https://github.com/JuliaRegistries/RegistryTools.jl/commit/f34de60b00741f86c1c77e4b188ab0a99477bc97).  Since this package is used by some important things like BB and JuliaRegistrator, it would be good to get some more end-to-end tests going.

How should we do this?  We obviously don't want to be opening pull requests to General every time we make a commit here, but perhaps we can create a fork and manipulate the pull requests there?

**Comment by GunnarFarneback** [comment]
There's no need to have a fork of the entire General registry to test the full `register` codepath. It is enough to have *a* registry, which can be very tiny, and it can be referenced by a file URL. Since this is the RegistryTools package all the tools to create a small registry are readily available :-). I have implemented such a test as part of #16.
