### ISSUE TITLE
Broken on `master`: `Pkg.Display` does not exist

### ISSUE THREAD

**Issue by staticfloat** [JuliaRegistries/RegistryTools.jl#24]
This line:

https://github.com/JuliaRegistries/RegistryTools.jl/blob/139e9eefd29f029d068aedc39ba3b7c72ee7ee58/src/register.jl#L529

Doesn't work on `master`, because `Pkg.Display` doesn't exist anymore.  If I'm understanding the code correctly, perhaps the analogous method from `BinaryBuilder` would be helpful here:

https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/ac292e96d1ce8a5354b61cfa115ed210ad7d0821/src/BinaryBuilder.jl#L117-L132

**Comment by GunnarFarneback** [comment]
That function is quite sketchy after the split of RegistryTools from Registrator. A more interesting question is maybe how useful it is to have the sha in the registration commit message. Sure, we can see that the deployed Registrator is running a version from May 17 last year, but does it actually help anyone to have that information there? If not the function can just be removed since it doesn't have any other use.
