### ISSUE TITLE
Project.toml needs compat entry for Pkg (or julia)

### ISSUE THREAD

**Issue by iamed2** [JuliaRegistries/RegistryTools.jl#52]
The current code requires access to the `tree_hash` field of `PackageEntry`, which was added in Pkg 1.2. However, there is no compat listed for Pkg, and julia compat is listed as 1.1 which has a corresponding 1.1 version of Pkg. 

I'm not sure whether it's best to add a julia compat requirement or a Pkg compat requirement but I think one or the other should be added so people with older Julia versions get an error on build when they need to upgrade (we only discovered this error at runtime after deploying a new version of registrator with Julia 1.1). We have no problem updating our Julia version in this case but we'd ideally like to avoid breaking our production registrator because of compatibility issues.

Does this package now require Julia 1.4? I see it's only tested that far back.

**Comment by GunnarFarneback** [comment]
My mistake from #28.

I'd rather fix this than increase compat, which would have to be on Julia itself since Pkg is a stdlib.

The simplest workaround is to add a `VERSION` check to https://github.com/JuliaRegistries/RegistryTools.jl/blob/4649e144a5a8f2e75b947f94cda4e178aa900982/src/register.jl#L541 and just return `"unknown"` with 1.1.

Alternatively we get rid of the whole printing tree hash diagnostic business. It's kind of sketchy in the first place.
